project:
  type: website

website:
  title: "UKFE training materials"
  description: "Training materials"
  repo-url: https://github.com/agqhammond/ukfe-training-materials
  repo-actions: [edit, issue]
  repo-subdir: "docs"
  page-navigation: true
  sidebar:
    contents:
      - href: index.qmd

theme:
  light: cosmo
  dark: darkly
